services:
  db:
    image: postgres:16
    restart: always
    container_name: litellm-db
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: ccproxy
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - ccproxy-litellm-db:/var/lib/postgresql/data # Persists Postgres data across container restarts

volumes:
  ccproxy-litellm-db:
