"""Type stubs for httpx library."""

from types import TracebackType
from typing import Any

class Response:
    status_code: int
    def json(self) -> dict[str, Any]: ...

class ConnectError(Exception): ...
class TimeoutError(Exception): ...

class Client:
    def __init__(self, timeout: float | None = None) -> None: ...
    def __enter__(self) -> Client: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def get(self, url: str, timeout: float | None = None) -> Response: ...
