"""Type stubs for tiktoken."""

class Encoding:
    def encode(self, text: str) -> list[int]: ...

def encoding_for_model(model: str) -> Encoding: ...
def get_encoding(encoding_name: str) -> Encoding: ...
