"""Type stubs for fasteners package."""

from pathlib import Path
from typing import Any

class InterProcessLock:
    """A file-based lock for inter-process synchronization."""

    def __init__(self, path: str | Path) -> None: ...
    def __enter__(self) -> InterProcessLock: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def acquire(self, blocking: bool = True, timeout: float | None = None) -> bool: ...
    def release(self) -> None: ...
    @property
    def acquired(self) -> bool: ...
